FROM xutl/ubuntu:xenial

LABEL maintainer="xutongle@gmail.com"

ARG HTTPD_VERSION

# Environment settings
ENV HTTPD_VERSION=${HTTPD_VERSION:-2.4.29}
ENV HTTPD_TGZ_URL http://mirrors.hust.edu.cn/apache/httpd/httpd-${HTTPD_VERSION}.tar.gz
ENV HTTPD_INI_DIR=/usr/local/apache/conf

# persistent / runtime deps
ENV PHPIZE_DEPS autoconf dpkg-dev file g++ gcc libc-dev make pkg-config re2c

RUN set -x \
#	&& sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		$PHPIZE_DEPS \
		curl \
		libssl1.0.0 \
		libedit2 \
		libsqlite3-0 \
		libxml2 \
		libxslt1.1 \
		libtidy-0.99-0 \
		libjpeg8 \
		libpng12-0 \
		libcurl3 \
		libbz2-1.0 \
		libfreetype6 \
		libgmp10 \
		libedit2 \
		libzip4 \
		libpcre3 \
		libzip4 \
		expat \
	&& rm -r /var/lib/apt/lists/*

RUN cd /usr/local/src \
	&& curl -fSL https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz -o libiconv-1.15.tar.gz \
	&& tar zxf libiconv-1.15.tar.gz \
	&& rm -rf libiconv-1.15.tar.gz \
	&& cd libiconv-1.15/ \
	&& ./configure --prefix=/usr/local --libdir=/usr/local/lib64 --enable-static \
	&& make -j "$(nproc)" \
	&& make install \
	&& rm -rf /usr/local/src/libiconv-1.15

RUN set -xe \
	&& buildDeps=" \
		libpcre3-dev \
		libzip-dev \
		libcurl4-openssl-dev \
		libssl-dev \
		libexpat1-dev \
	" \
#	&& sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/' /etc/apt/sources.list \
	&& apt-get update && apt-get install -y --no-install-recommends --no-install-suggests $buildDeps && rm -r /var/lib/apt/lists/* \
	\
	&& AprVersion=1.6.3 \
		AprUtilVersion=1.6.1 \
	&& cd /usr/local/src \
	&& curl -fSL ${HTTPD_TGZ_URL} -o httpd-${HTTPD_VERSION}.tar.gz \
	&& tar zxf httpd-${HTTPD_VERSION}.tar.gz \
	&& rm -rf httpd-${HTTPD_VERSION}.tar.gz \
	&& cd httpd-${HTTPD_VERSION}/srclib \
	&& curl -fSL http://mirrors.hust.edu.cn/apache/apr/apr-${AprVersion}.tar.gz -o apr-${AprVersion}.tar.gz \
	&& curl -fSL http://mirrors.hust.edu.cn/apache/apr/apr-util-${AprUtilVersion}.tar.gz -o apr-util-${AprUtilVersion}.tar.gz \
	&& tar zxf apr-${AprVersion}.tar.gz \
	&& tar zxf apr-util-${AprUtilVersion}.tar.gz \
	&& mv apr-${AprVersion} apr \
	&& mv apr-util-${AprUtilVersion} apr-util \
	&& rm -f apr-${AprVersion}.tar.gz \
	&& rm -f apr-util-${AprUtilVersion}.tar.gz \
	&& cd /usr/local/src/httpd-${HTTPD_VERSION}/ \
	&& ./configure \
		--prefix=/usr/local/apache \
		--enable-mods-shared=most \
		--enable-headers \
		--enable-mime-magic \
		--enable-proxy \
		--enable-so \
		--enable-rewrite \
		--enable-ssl \
		--enable-deflate \
		--with-pcre \
		--with-included-apr \
		--with-apr-util \
		--enable-mpms-shared=all \
		--enable-remoteip \
	&& make -j "$(nproc)" \
	&& make install \
	&& rm -rf /usr/local/src/httpd-${HTTPD_VERSION} \
	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $buildDeps

EXPOSE 80